import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
           <header className="bg-gray-900 text-white">
          <nav className="max-w-7xl mx-auto flex justify-between items-center p-4">
            <div className="text-2xl font-bold uppercase">LK.</div>
            <ul className="flex space-x-6">
              <li><a href="/" className="hover:text-yellow-500">Home</a></li>
              <li><a href="/about" className="hover:text-yellow-500">About</a></li>
              <li><a href="/contact" className="hover:text-yellow-500">Contact</a></li>
            </ul>
          </nav>
        </header>
        {children}
        <footer className="bg-gray-800 text-white text-center py-4">
          &copy; 2024 LK. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
